### ISSUE TITLE
New website design

### ISSUE THREAD

**Issue by LankyBox01** [LankyBox01/scratch-trust#10]
# New design for the website

Desktop:
![Desktop Prototype](https://user-images.githubusercontent.com/79767244/147698748-215278dd-612e-4d14-bfb0-14c80f2ec332.jpg)

Mobile:
![Mobile Prototype](https://user-images.githubusercontent.com/79767244/147698750-4420b114-1d67-43b4-a36c-2f33404453f7.jpg)

I need some reviews before a commit

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147698910-a7b35063-1e68-479f-ac69-a055c892ef40.png)
you can use mine as a scratch theme.

**Comment by LankyBox01** [comment]
what are we using the nav bar for?

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147699029-faa52e36-b24d-4755-b240-0c5171ac3109.png)
it can either be a navbar with some links or just a header bar

**Comment by LankyBox01** [comment]
Well why are we changing the entire layout for a scratch theme, i don't get it

**Comment by JaydenDev** [comment]
@LankyBox01 my index.html isn't the same as yours, I had to change it.

**Comment by JaydenDev** [comment]
I'll get the layout right soon tho!

**Comment by JaydenDev** [comment]
send me an screenshot of ur layout

**Comment by LankyBox01** [comment]
what

**Comment by LankyBox01** [comment]
Look, i don't think we can use tailwinds or whatever framework you're using. It's just confusing.

**Comment by JaydenDev** [comment]
want it all centered or on the left?
@LankyBox01 you dont have to do anything im making the theme myself.

**Comment by JaydenDev** [comment]
surely later you can have a theme switch button with a function to switch stylesheets

**Comment by LankyBox01** [comment]
hey wait

**Comment by JaydenDev** [comment]
considering its an entirely different HTML file that might not work.
actually a button to redirect to the other HTML file (the one with the scratch theme) might work.

**Comment by LankyBox01** [comment]
if i wanted a scratch theme,

**Comment by JaydenDev** [comment]
ur gonna make ur own? k.

**Comment by LankyBox01** [comment]
why wouldnt i just change the colors

**Comment by LankyBox01** [comment]
you're making effort for no reason

**Comment by JaydenDev** [comment]
g o o d p o i n t

**Comment by LankyBox01** [comment]
if you wanna use tinwhales, just jump on the dashboard topic.

**Comment by JaydenDev** [comment]
Well anyway tailwind gets quite confusing when I move away from the code i took from webdev03

**Comment by LankyBox01** [comment]
you stole code?

**Comment by JaydenDev** [comment]
@LankyBox01 No its form searchocean, I'm pretty sure I took most of it from the docs.

**Comment by JaydenDev** [comment]
*from
searchocean is my project.

**Comment by LankyBox01** [comment]
okay

**Comment by LankyBox01** [comment]
i want you to review the current prototype i made

**Comment by JaydenDev** [comment]
Scratch Theme
- Set Header to Blue (Already Is
- Make BG white (Already Is)
- Make accent blue (Already is)

**Comment by JaydenDev** [comment]
your scratch theme is already done.

**Comment by JaydenDev** [comment]
you can make a gh-pages branch and put the code in it, then you'll have lankybox01.github.io/scratch-trust being hosted.

**Comment by JaydenDev** [comment]
if you want I can get the GH pages set up on my site.

**Comment by JaydenDev** [comment]
nvm ur gh pages page is already setup

**Comment by JaydenDev** [comment]
are you going to commit your latest code?

**Comment by LankyBox01** [comment]
> are you going to commit your latest code?

which

**Comment by LankyBox01** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
				<meta charset="UTF-8">
				<title>ForumsFeed</title>
				<style>
								body {
								font-family: Helvetica;
								margin: 0;
								}
								
								.header {
								background-color: #4287f5;
								color: white;
								padding: 10px 20px;
								}
								
								.page {
								padding: 15px 20px;
								}

          input, button {
          border-radius: 20px;
          border: 1.5px solid lightgrey;
          padding: 5px;
          }

          button {
          background-color: #4287f5;
          color: white;
          border: 1.5px solid #2b60b5;
          }
				</style>
				<script src="script.js"></script>
</head>
<body>
				<div class="header">
								<h1>ForumsFeed</h1>
				</div>
				<div class="page">
								Welcome to <b>ForumsFeed</b>! ForumsFeed is a simple tool to measure your (or someone else's) level of trustworthyness on the <a href="https://scratch.mit.edu/discuss">Scratch Discussion Forums</a>.
								<br><br>
								<input placeholder="Scratch username..." id="username" /> <button onclick="getworth(document.getElementById('username').value)">Measure!</button>
								<hr style="border: 1px dotted lightgrey;margin-top:20px;margin-bottom:20px" />
								<b>How does this work?</b>
								<br>
								Using <a href="https://scratchdb.lefty.one">ScratchDB</a>, we take the post count of the requested user and return the level based on the number of posts the user has.<br><br>
								<b>How many levels are there?</b>
								<br>
								There are currently <u>7 levels</u> measured. They are decided based on your post count. Which level are you?
								<ul>
												<li>Veteran - 30,000+ Posts</li>
												<li>Experienced - 10,000+ Posts</li>
												<li>Trusty - 5,000+ Posts</li>
												<li>Helper - 1,000+ Posts</li>
								  			<li>Assistive Trainee - 500+ Posts</li>
			  							 	<li>Trainee - 100+ Posts</li>
								 				<li>Newcomer - 0+ Posts</li>
								</ul>
								<b>Can i contribute?</b>
								<br>
								<i>Yes!</i> We have a lot of issues to fix, so we really do appreciate pull requests and contributors. <a href="https://github.com/LankyBox01/scratch-trust/">https://github.com/LankyBox01/scratch-trust/</a>
				</div>
</body>
</html>
```

Could you please pr this code to index.html?

**Comment by webdev03** [comment]
@JaydenDev You can go in the repository settings and turn it on for any branch, `gh-pages` branch is optional.

**Comment by JaydenDev** [comment]
@LankyBox01 what you should do is install git and commit your changes that way instead of copy paste from vscode.
