### ISSUE TITLE
My 2 cents

### ISSUE THREAD

**Issue by Mbrick2** [LankyBox01/scratch-trust#17]
Add discussion tab
Give someone else write access (for emergencys)

**Comment by JaydenDev** [comment]
@Mbrick2 here's a story for when I gave someone other than me write access to my repository

They added useless files to the repo like CITATION.ctf that served no purpose. Broke my project twice. And oh my god, it was a MESS. Always maintain yourself, have control over the flow. Keep it organized.

**Comment by webdev03** [comment]
At this stage having someone else with write access is unneccessary. @JaydenDev that's a problem with the contributor you gave access to and not everyone does that.

But of course, when you give write access, you will need a lot of trust in that person.

**Comment by LankyBox01** [comment]
^^^^
Personally, i never trust anyone with abilities as such.

**Comment by LankyBox01** [comment]
> Add discussion tab

Bruh. Why do we need this? We've got issues. What does it add? Just a new priority and waste of time.

**Comment by JaydenDev** [comment]
> > Add discussion tab
> 
> Bruh. Why do we need this? We've got issues. What does it add? Just a new priority and waste of time.

Failure to acknowledge, or consideration of ideas of other users is not the way to maintain a repository properly. Especially not an open source one.

The discussions page, is where people can discuss features and the like without having to flood the issues tab with what could be going in discussions. Think of it as a forum.

**Comment by LankyBox01** [comment]
> > > Add discussion tab
> > 
> > 
> > Bruh. Why do we need this? We've got issues. What does it add? Just a new priority and waste of time.
> 
> Failure to acknowledge, or consideration of ideas of other users is not the way to maintain a repository properly. Especially not an open source one.
> 
> The discussions page, is where people can discuss features and the like without having to flood the issues tab with what could be going in discussions. Think of it as a forum.

Right.

**Comment by Mbrick2** [comment]
SO Discussion Tab it is
