### ISSUE TITLE
Auto translate

### ISSUE THREAD

**Issue by Quantum-Codes** [LankyBox01/scratch-trust#18]
Why manually translate this page when you could auto translate by using Google translate? 

https://stackoverflow.com/questions/65705315/how-do-i-automatically-translate-my-website-into-the-users-language

If it's okay, then make this into the site

**Comment by kccuber-scratch** [comment]
Google Translate is not very accurate

**Comment by LankyBox01** [comment]
https://scratch.mit.edu/discuss/topic/568146/?page=6#post-5907077

**Comment by Quantum-Codes** [comment]
> Google Translate is not very accurate

I literally made my school project with Google translate to translate to another language(the subject). 

All I know is that it translated way better than I could (used better words)

**Comment by Quantum-Codes** [comment]
> https://scratch.mit.edu/discuss/topic/568146/?page=6#post-5907077

Make a discussion tab on this repo. It will be useful. 

_not to mention im banned from scratch_
