### ISSUE TITLE
Add a LICENSE.txt

### ISSUE THREAD

**Issue by Steve0Greatness** [LankyBox01/scratch-trust#20]
While this is under the CC by 4.0 license, a `LICENSE.txt` makes it so that you don't have to go outside of Github to understand the license.

**Comment by LankyBox01** [comment]
no license template for CC BY 4.0

**Comment by webdev03** [comment]
Can `CC BY 4.0` be used for code? Wouldn't it be something like MIT or GPL?

**Comment by webdev03** [comment]
@LankyBox01 https://creativecommons.org/licenses/by/4.0/legalcode

**Comment by JaydenDev** [comment]
It would be LICENSE not LICENSE.txt

**Comment by JaydenDev** [comment]
#23

**Comment by LankyBox01** [comment]
added

**Comment by webdev03** [comment]
@JaydenDev `LICENSE.txt`, `LICENSE.md`, `LICENSE.txt`, and `LICENSE` are all valid.
