### ISSUE TITLE
Translating the site into your language

### ISSUE THREAD

**Issue by LankyBox01** [LankyBox01/scratch-trust#24]
Hello! So you're trying to become a translator for ForumsFeed?

All you need to do is fill out this form, and follow the instructions provided.
```
### Form
**First name**:

**Age**:

**Scratch account**:

**Your fluent language**:

**Your country**:


### Translating Instructions
Go to [this scratch post](https://scratch.mit.edu/discuss/topic/568146/?page=7#post-5908063) and translate all of the sentences, words, paragraphs, and other texts provided, except for the header.
Then, go to the Translated Result section on this form and write the translation.

### Translated Result
...
```

Once you have filled this form out, please send it here.
Thanks for considering being a translator!

**Comment by JaydenDev** [comment]
May I ask why you need "age", that's a suspicious thing to be asked on the internet.

**Comment by LankyBox01** [comment]
> May I ask why you need "age", that's a suspicious thing to be asked on the internet.

bruh what

**Comment by JaydenDev** [comment]
btw you can't have markup/markdown in a triple ticks

**Comment by LankyBox01** [comment]
suspicious? Is it a crime to know how old the translator is?

**Comment by JaydenDev** [comment]
No, most people will refuse to tell. Safety.

**Comment by LankyBox01** [comment]
> btw you can't have markup/markdown in a triple ticks

yes i know, it's for the comment

**Comment by LankyBox01** [comment]
WHAT

**Comment by LankyBox01** [comment]
MOST PPL WILL REFUSE TONTELL??

**Comment by JaydenDev** [comment]
I don't know don't ask me

**Comment by LankyBox01** [comment]
ONLY YOU WILL REFUSE TO TELL

**Comment by LankyBox01** [comment]
YOU SAID IT, DON'T SAY DON'T ASK ME

**Comment by LankyBox01** [comment]
BRUH

**Comment by JaydenDev** [comment]
why? spamming caps. how many times do i need to say this. not the way to maintain a repository

**Comment by JaydenDev** [comment]
I'm just saying some people are scared to say their age online what's your problem. I was just letting you know.

**Comment by JaydenDev** [comment]
Also, I will mention. You said I act like a 10 year old. Please take the time to look through your own comments.

**Comment by LankyBox01** [comment]
> I'm just saying some people are scared to say their age online what's your problem. I was just letting you know.

I have two issues with that statement
1. So age is private info but first name isn't?
2. Who says it's required? Does it really matter? Is there like, a star next to it saying its required or something?
