### ISSUE TITLE
Create a Stylesheet

### ISSUE THREAD

**Issue by Steve0Greatness** [LankyBox01/scratch-trust#30]
Stylesheets are very useful, and allow you not to have huge style tags in every html file.

Edit: Stylesheets are easy to make, all you need to do is create a `style.css` file, then, to have it affect your HTML file, use `<link rel="stylesheet" href="/path/to/style.css">`

Just so you know, I've made one in [my fork of this repo](/Steve0Greatness/scratch-trust).

**Comment by LankyBox01** [comment]
added, thanks
