### ISSUE TITLE
Simple forumer randomiser

### ISSUE THREAD

**Issue by LankyBox01** [LankyBox01/scratch-trust#4]
```
let scratchers = ["Za-Chary", "Paddle2See", "Cheddargirl", "griffpatch", "Chrisg", "Ceebee", "ScratchCat", "BearSlothCoding", "deck26", "catsunited", "Sigton", "harakou", "maximouse", "makethebrainhappy", "mybearworld", "gosoccerboy5", "PATSATDAT", "nampinanathali", "Chiroyce", "ajsya", "MagicCrayon9342", "yes-i-am-lanky", "han614698", "dertermenter", "dhuls", "orangetheory", "ScratchCat1038", "yeetoburro1", "Bluebatstar", "-EmeraldThunder-", "CST1229"];
```

We could have a button to randomly select a scratcher for users to test the site.

**Comment by JaydenDev** [comment]
you can just
https://www.geeksforgeeks.org/how-to-select-a-random-element-from-array-in-javascript/

**Comment by LankyBox01** [comment]
> you can just https://www.geeksforgeeks.org/how-to-select-a-random-element-from-array-in-javascript/

I know, that's exactly what we're doing.

**Comment by webdev03** [comment]
`const` would be better

**Comment by JaydenDev** [comment]
If you still want to consider my scratch theme for this site let me know.

**Comment by JaydenDev** [comment]
Here's a good example of randomized selection from an array
https://github.com/JaydenDev/randmsg

**Comment by JaydenDev** [comment]
@webdev03, what's the difference between let, constant, and var anyway

**Comment by LankyBox01** [comment]
> Here's a good example of randomized selection from an array https://github.com/JaydenDev/randmsg

Mate, I've been coding since i was 7, I've did this procedure thousands of times.



> @webdev03, what's the difference between let, constant, and var anyway

Haha well, there's quite a big difference.

var declarations are globally scoped or function scoped while let and const are block scoped.
var variables can be updated and re-declared within its scope; let variables can be updated but not re-declared; const variables can neither be updated nor re-declared.
They are all hoisted to the top of their scope. But while var variables are initialized with undefined, let and const variables are not initialized.
While var and let can be declared without being initialized, const must be initialized during declaration.

www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

**Comment by JaydenDev** [comment]
Sorry, I don't know what scope or scoped means :/

**Comment by webdev03** [comment]
I'd like to add that `const` if it is ```js
{ foo: "bar", baz: "item" }
```
you can still change `foo` and `baz`.
