### ISSUE TITLE
Lower the veteran level requirement

### ISSUE THREAD

**Issue by LankyBox01** [LankyBox01/scratch-trust#6]
> Might want to lower down everything. only deck26 is vetrean
https://github.com/LankyBox01/scratch-trust/issues/2#issuecomment-1002662276

I agree with this.

**Comment by Quantum-Codes** [comment]
15k might be great. That way, 3 people will get veteran. 

Also getting veteran should be difficult

**Comment by LankyBox01** [comment]
> 15k might be great. That way, 3 people will get veteran.
> 
> Also getting veteran should be difficult

Yes, i love that.
