### ISSUE TITLE
Upgrade to CSS Framework

### ISSUE THREAD

**Issue by LankyBox01** [LankyBox01/scratch-trust#8]
> you should use tailwind CSS
[#62 (post)](https://scratch.mit.edu/discuss/topic/568146/?page=4#post-5902267)

**Comment by JaydenDev** [comment]
It's fairly easy to do

1. Delete the existing stylesheet and remove the line in the HTML file where the stylesheet is linked
2. (Temporary) Add ```<script src="cdn.tailwindcss.com"></script>``` to the HEAD of your HTML file
3. Tailwind has a variety of CSS classes you apply to elements, read the tailwind documentation to get the classes you want to use to style your site. Simply apply the classes to HTML elements. Once you are done converting to tailwind, set up permanent method. Ask @webdev03 about that (god286 on scratch).

**Comment by LankyBox01** [comment]
@JaydenDev Hmm... well, i think it would be better for us to make our own style sheet instead of using an external framework. It will save us plenty of time, and we won't have to dig throughout the documentation each time we want to make a change.

**Comment by JaydenDev** [comment]
@LankyBox01 
Tailwind Examples
https://github.com/JaydenDev/Catalyst
https://github.com/JaydenDev/searchocean

Tailwind is good.

**Comment by JaydenDev** [comment]
It's all worth it in the end.

**Comment by JaydenDev** [comment]
```html
<body class="p-2 bg-indigo-500">
  <div id="center-container" class="grid text-center justify-center">
    <div id="header">
      <h1 class="text-2xl font-semibold">Search Ocean</h1>
    </div>

    <div class="flex w-full flex-wrap items-stretch mb-3 justify-center space-x-2">
      <input
        class="px-3 py-3 placeholder-white text-white relative bg-red-500 rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring w-50"
        id="searchbar" list="data" placeholder="Start searching..."><button
        class="px-3 py-3 w-50 bg-red-500 text-white rounded" onClick="search()" id="searchbar-gobutton">Go</button>
    </div>
    <br>
    <br>
    <div class="flex w-full flex-wrap space-x-2 items-stretch mb-3 justify-center">
      <input id="enginebar"
        class="px-3 py-3 placeholder-white text-white relative bg-red-500 rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring w-50"
        placeholder="https://google.com/search?q="><button class="px-3 py-3 w-50 bg-red-500 text-white rounded" style="animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite;"
        onClick="engineSel()">Select</button>
    </div>
    <br>
    <br>
    <div class="flex w-full flex-wrap items-stretch mb-3 justify-center space-x-2">
      <button class="px-3 py-3 w-50 bg-red-500 text-white rounded" onClick="ddg()" id="ddg">DDG</button>
      <button class="px-3 py-3 w-50 bg-red-500 text-white rounded" onClick="bing()" id="bing">BING</button>
      <button class="px-3 py-3 w-50 bg-red-500 text-white rounded" onClick="qwant()" id="qwant">QWANT</button>
    </div>
```
A code snippet from SearchOcean that might be useful. It's 2 input boxes and 5 buttons but I can cut it down to just an input box and button.

**Comment by JaydenDev** [comment]
```html
<body class="p-2 bg-indigo-500">
  <div id="center-container" class="grid text-center justify-center">
    <div id="header">
      <h1 class="text-2xl font-semibold">Search Ocean</h1>
    </div>

    <div class="flex w-full flex-wrap items-stretch mb-3 justify-center space-x-2">
      <input
        class="px-3 py-3 placeholder-white text-white relative bg-red-500 rounded text-sm border-0 shadow outline-none focus:outline-none focus:ring w-50"
        id="inputbox01" placeholder="Type Username"><button
        class="px-3 py-3 w-50 bg-red-500 text-white rounded" onClick="whatEverFunction" id="button01">Go</button>
    </div>
```

**Comment by LankyBox01** [comment]
@JaydenDev Those examples make me want to make my own stylesheet

**Comment by JaydenDev** [comment]
@LankyBox01 your going to end up making a framework if you use your own CSS anyway...

**Comment by LankyBox01** [comment]
actually

**Comment by LankyBox01** [comment]
if you wanna use tailwindcss,

**Comment by LankyBox01** [comment]
make a pr

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/147695927-925b41bd-59c1-4dda-8e1f-7f8150326f2c.png)
this is what the code snippet I posted looks like.

**Comment by LankyBox01** [comment]
I don't like those small rounded corners. It's either fully round sides or square

**Comment by JaydenDev** [comment]
why?

**Comment by LankyBox01** [comment]
It doesn't feel right. Plus, I'm already sketching the page and have a few prototypes prepared.

**Comment by LankyBox01** [comment]
![first mobile sketch](https://user-images.githubusercontent.com/79767244/147696838-97492f28-782c-4c46-b2d5-57f9b11c32a7.jpg)

**Comment by JaydenDev** [comment]
Did you do it with tailwind?

**Comment by JaydenDev** [comment]
If not, how did you make a such a good UI without tailwind?

**Comment by LankyBox01** [comment]
> If not, how did you make a such a good UI without tailwind?

Skills, bitch.

**Comment by LankyBox01** [comment]
Seriously, though. This was really easy to make.

**Comment by webdev03** [comment]
I can make a proper tailwind.
